name: HangPoint CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore
        working-directory: ./backend/HangPoint.API

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./backend/HangPoint.API

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Get packages
        run: flutter pub get
        working-directory: ./frontend/hangpoint_app

      - name: Build Flutter Web
        run: flutter build web --release
        working-directory: ./frontend/hangpoint_app